FORMAT: 1A
HOST: http://localhost:3000

# user

Get user information by providing the ID.

## User List [/user/{id}]

### Get User Data [GET]
+ Parameters
    + id: 2 (number, required) - ID of user
    
+ Response 200 (content-type: application/json;charset=utf-8)

        [
            {
                "first_name" : "bob",
                "last_name" : "builder",
                "email" : "bob@email.com"
            }
        ]

### Put user data [PUT]
+ Parameters
    + id: 2 (number, required) - ID of user



+ Request (application/json)

        [
            {
                "first_name" : "bob",
                "last_name" : "builder",
                "email" : "bob@email.com"
            }
        ]

+ Response 200 (application/json)